(maint) Updating changelog generator config
puppetlabs/puppetlabs-postgresql pull request #1280
Opened 2021-06-21 16:20 UTC by pmcmaw

2021-06-21 16:37 UTC, ekohl reviewed
I would expect to see a change in `Rakefile` to reflect this.

2021-06-25 09:13 UTC, ekohl submitted a review, later dismissed

2021-06-28 12:38 UTC, pmcmaw commented
Note - failures in spec tests are unrelated to this PR.

2021-06-29 09:46 UTC, alexjfisher commented
I'd recommend just fixing the formatting of line 1 of the HISTORY.MD file.
https://github.com/puppetlabs/puppetlabs-postgresql/blame/main/HISTORY.md#L1

Then `since_tag` will be automatically picked up.

2021-06-29 14:01 UTC, DavidS commented
> I'd recommend just fixing the formatting of line 1 of the HISTORY.MD file.
> https://github.com/puppetlabs/puppetlabs-postgresql/blame/main/HISTORY.md#L1
> 
> Then `since_tag` will be automatically picked up.

Fix to what?

2021-06-29 15:03 UTC, alexjfisher commented
> > I'd recommend just fixing the formatting of line 1 of the HISTORY.MD file.
> > https://github.com/puppetlabs/puppetlabs-postgresql/blame/main/HISTORY.md#L1
> > Then `since_tag` will be automatically picked up.
> 
> Fix to what?

I think just adding a release date in brackets should do it.  Will have a go later.

2021-06-29 15:18 UTC, alexjfisher commented
> > > I'd recommend just fixing the formatting of line 1 of the HISTORY.MD file.
> > > https://github.com/puppetlabs/puppetlabs-postgresql/blame/main/HISTORY.md#L1
> > > Then `since_tag` will be automatically picked up.
> > 
> > 
> > Fix to what?
> 
> I think just adding a release date in brackets should do it. Will have a go later.

Actually, it's fine as is (without adding a date).  It's already being correctly parsed from HISTORY.md.

2021-06-29 15:20 UTC, alexjfisher requested changes

2021-06-29 15:20 UTC, alexjfisher commented on .sync.yml
> +  changelog_since_tag: '5.3.0'
This is actually redundant.  The HISTORY.md file is formatted in such a way that this will be automatically discovered.

2021-06-29 15:20 UTC, alexjfisher commented on Rakefile
> +    config.since_tag = "5.3.0"
This line can go too.

2021-07-02 14:28 UTC, alexjfisher approved these changes

2021-07-02 14:30 UTC, ekohl approved these changes
Yay for less code.

2021-07-05 14:00 UTC, merged