define Enum on supported encryption types for postgresql_password
puppetlabs/puppetlabs-postgresql pull request #1611
Opened 2024-08-30 09:45 UTC by figless

## Summary
This PR fixes [1575](https://github.com/puppetlabs/puppetlabs-postgresql/issues/1575)

## Additional Context

## Related Issues (if any)

## Checklist
I was hitting [1575](https://github.com/puppetlabs/puppetlabs-postgresql/issues/1575) when using a Deferred password. With this fix, puppet creates the database as before (v9.2.0)

```
postgresql::server::db { $db_name:
      user     => $db_username,
      password => Deferred('unwrap', [$db_password]),
}
```

2024-08-30 09:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/puppetlabs-postgresql?pullRequest=1611) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/puppetlabs-postgresql?pullRequest=1611) before we can accept your contribution.<br/><hr/>**Ben Morrice** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/puppetlabs-postgresql?pullRequest=1611) it.</sub>

2024-09-02 10:57 UTC, ekohl requested changes
We already have defined this as an enum:
https://github.com/puppetlabs/puppetlabs-postgresql/blob/05a78097377eebd34297e9a01054f4bd50507b79/types/pg_password_encryption.pp#L2

And it's used in multiple places now, so this would risk them going out of sync. I'd at least expect a comment in both places to remind people to keep them in sync.

2024-10-28 08:27 UTC, figless commented
> We already have defined this as an enum:
> 
> https://github.com/puppetlabs/puppetlabs-postgresql/blob/05a78097377eebd34297e9a01054f4bd50507b79/types/pg_password_encryption.pp#L2
> 
> And it's used in multiple places now, so this would risk them going out of sync. I'd at least expect a comment in both places to remind people to keep them in sync.

I've added a comment to both files.

2024-10-28 12:14 UTC, bastelfreak commented
Is there a chance you can add a test with `Deferred()`, to ensure this doesn't break in the future?

2024-10-29 14:52 UTC, figless commented
> Is there a chance you can add a test with `Deferred()`, to ensure this doesn't break in the future?

Sure - i've copied `spec/acceptance/db_spec.rb` to `spec/acceptance/db_deferred_spec.rb` and configured the test to use a `Deferred` password.

2024-10-30 08:26 UTC, figless commented
The previous code in `db_deferred_spec.rb` failed the CI, even though it was essentially a copy from `db_spec.rb`....
I have adapted the code, which now passes locally.

2025-01-10 21:22 UTC, smortex commented
I can't trigger the CI, maybe because the branch is outdated. Let's try to rebase it…

2025-01-11 12:40 UTC, ekohl commented
I needed to approve ci, which I just did

2025-04-01 11:53 UTC, figless commented
Hello,
I've just rebased this branch.
Can the CI please be retriggered?

2025-04-17 11:59 UTC, bastelfreak approved these changes

2025-04-17 12:06 UTC, closed without merging

2025-10-22 15:36 UTC, alexjfisher commented
> We already have defined this as an enum:
> 
> https://github.com/puppetlabs/puppetlabs-postgresql/blob/05a78097377eebd34297e9a01054f4bd50507b79/types/pg_password_encryption.pp#L2
> 
> And it's used in multiple places now, so this would risk them going out of sync. I'd at least expect a comment in both places to remind people to keep them in sync.

Is it worth explicitly spelling out that type aliases can't be used in functions if you ever want the function call to be deferred? (Since types aren't plugin-synced to the agent)

2025-10-23 11:13 UTC, alexjfisher commented
I've rebased/squashed and tidied up the commit message.
@ekohl Would you take another look?

2025-10-23 11:41 UTC, ekohl commented on spec/acceptance/db_deferred_spec.rb
> +    <<-MANIFEST.unindent
```suggestion
    <<~MANIFEST
```

2025-10-23 11:42 UTC, ekohl commented on spec/acceptance/db_deferred_spec.rb
> +    end
I wouldn't care about Puppet 6 and older
```suggestion
```

2025-10-23 11:42 UTC, ekohl commented on spec/acceptance/db_deferred_spec.rb
> +      $database = #{database}
While it works, I'd avoid bare strings:
```suggestion
      $user = '#{user}'
      $password = '#{password}'
      $database = '#{database}'
```

2025-10-23 16:33 UTC, alexjfisher commented
> Some small implementation notes, but overall it looks ok.

Fixed those up.  Good to merge?